# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

# Set up renv following instructions at https://www.emilhvitfeldt.com/post/bookdown-netlify-github-actions/
on:
  push:
    branches: [main, master, ch7_8_updates]
  pull_request:
    branches: [main, master, ch7_8_updates]
  workflow_dispatch:

name: bookdown

jobs:
  bookdown:
    runs-on: macOS-latest
    # Only restrict concurrency for non-PR jobs
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
      EMAIL: ${{ secrets.EMAIL }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Install XQuartz on macOS
        if: runner.os == 'macOS'
        run: brew install xquartz --cask

      - name: Install tinytex
        run: |
          tinytex::install_tinytex()
        shell: Rscript {0}

      - name: Set up TinyTeX and packages
        run: |
          export PATH=$HOME/.TinyTeX/bin/x86_64-darwin:$PATH
          tlmgr install upquote
          tlmgr update --self
          tlmgr update --all
          updmap-sys

      - name: Install Inconsolata font if not present
        run: |
          if ! tlmgr list --installed | grep -q inconsolata; then
            tlmgr install inconsolata
            updmap-sys
          fi
        shell: bash

      - name: Test Inconsolata font in LaTeX
        run: |
          echo "\documentclass{article}\usepackage{inconsolata}\begin{document}Hello, Inconsolata!\end{document}" > test.tex
          pdflatex test.tex
          
      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Cache R Packages
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - uses: r-lib/actions/setup-renv@v2

      - name: Cache bookdown results
        uses: actions/cache@v3
        with:
          path: _bookdown_files
          key: bookdown-${{ hashFiles('**/*Rmd') }}
          restore-keys: bookdown-

      - name: Build site
        run: bookdown::render_book("index.Rmd", quiet = TRUE)
        shell: Rscript {0}

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          branch: gh-pages
          folder: docs